name: Publish to npm

on:
  push:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18.16.0"

      - name: Install dependencies
        run: npm ci

      - name: Run test
        run: npm run test

      - name: Build
        run: npm run build

      - name: Increment version and tag commit
        run: |
          npm version patch --git-tag-version
          git push --follow-tags

      - name: Publish to npm
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
